### ISSUE TITLE
tcpClient.ConnectAsync cause Error

### ISSUE THREAD

**Issue by Eg-Virus** [1iveowl/SocketLite#17] opened 2017-12-28 17:48 UTC
Hi,
i tried to use it but i faced this error when i tried to connect from Android as mobile to Pi3 with WinIoT.
[ERROR] FATAL UNHANDLED EXCEPTION: System.NotImplementedException: This PCL uses the 'Bait and Switch pattern'.
the Pi3 has a listen module and the sending is in the Android, and the error happen in the connect.

**Comment by 1iveowl** [comment] 2018-02-01 00:06
You need to ensure that you apply the NuGet to the Android project too. This is how 'Bait and Switch works'. Please see the readme.

**Comment by Eg-Virus** [comment] 2018-02-06 09:00
I'm Adding the NuGet to all my projects and it's the same issue, so i downloaded the code of the ScoketLite and added it directly to the the projects (**the Interface and the Bait projects only of course** ) and everything working fine.
So i think something is not correct in the Nuget references.
I was trying .NETStander  from 1.5 to 2.0 trying to know where the problem but i couldn't.

**Comment by 1iveowl** [comment] 2018-02-11 10:21
@Eg-Virus I'm unable to local the cause of the issue. Could you please reprocude a miminun version of a project that has this issue and share it with me?

Thank you.

**Comment by Eg-Virus** [comment] 2018-02-14 13:49
@1iveowl 
This's the sample that i'm working now, try to run the the UWP and it will give you the error, may i'm missing something.
please note that i'm linking your projects not the nuget.
[https://github.com/Eg-Virus/Gateway](url)

**Comment by 1iveowl** [comment] 2018-02-14 14:48
Linking project and linking NuGet's is not the same. The NuGet spec takes care of matching the right dll with the right consumer. 

Also what version of UWP are you using? If you are targeting 16299+ then .NET Standard 2.0 will work for you.

**Comment by Eg-Virus** [comment] 2018-02-15 06:10
@1iveowl 
Sorry for the broken link, here's the good one [https://github.com/Eg-Virus/Gateway.git](url)

And Yes I'm using UWP 16299.

and yes i tried the nugets first for .NET Standard 2.0 but i faced the issue that we talking about and then i tried to downgrade the PCL but the issue still happening, so i decided to use the projects itself and made my project .NET Standard 1.5.

I think i'm missing something but i don't know.
i hope i explained my issue clearly to you.

**Comment by Eg-Virus** [comment] 2018-02-15 10:45
@1iveowl 
Ohhh, that's not my entire code :), i created this sample to just reproduce the issue and investigate it :).

the sample supposed to send/receive between any 2 of the 3 Apps(UWP, Android or iOS).
the problem happened when you start to send. the problem will says that there's no implementation.

**Comment by 1iveowl** [comment] 2018-02-15 11:15
OK. 

In you project you reference the project 'SocketLite.Bait.Netstandard'. This is incorrect. For UWP you must reference 'SocketLite.UWP'. This is exactly the mapping the NuGet is suppose to do for you.

For some reason your UWP project references NETStandard.Library 1.6.1 rather than NETStandard.Library 2.0.1. This might be why the NuGet is not mapping to the .NET Standard 2.0 version of SocketLite.  

Also Microsoft.NETCore.UniversalWindowsPlatform should probably be updated to 6.0.7.

Could you try these things and let me know if that makes a difference?

**Comment by 1iveowl** [comment] 2018-02-15 11:19
Please see comments about [UWP 16299 here](https://docs.microsoft.com/en-us/windows/uwp/updates-and-versions/choose-a-uwp-version)

**Comment by 1iveowl** [comment] 2018-02-15 11:30
I've created an update to SocketLite to version 4.1.5. 

I don't think it addresses you issue, as I still can identify the source of the issue, however it does include some house keeping I've been wanting to do. Anyhow, please give it a try.

**Comment by Eg-Virus** [comment] 2018-02-15 12:16
Good,
i have created another branch to use the NuGet and i'm trying to reproduce the issue and i'll update the NuGet as well but i have another problem of my own in the network and i'm trying to solve it that i can't make a connection and get exception "No connection could be made because the target machine actively refused it" and i think it's related to the firewall of the network.
once i do i'll give you the feedback.

**Comment by 1iveowl** [comment] 2018-02-20 15:04
Has the issue been solved? Any feedback?

Thank you.

**Comment by Eg-Virus** [comment] 2018-02-21 11:41
Sorry no news yet, my network in work is not helping right now, i get error that "No connection could be made because the target machine actively refused it" or there's not connection at all.

**Comment by 1iveowl** [comment] 2018-03-01 15:39
I am going to close this issue. Feel free to reopen when you are able to proceed.

**Comment by Eg-Virus** [comment] 2018-03-19 10:02
Hi again,
Sorry for being late in my responses.

right now i'm using only the nuget you updated and i have the same first error i faced "This PCL uses the 'Bait and Switch pattern'. This blog post offers great insights into this pattern: http://log.paulbetts.org/the-bait-and-switch-pcl-trick/"

the error is in the Android version:
My phone is OnePlus3 with Android 8.0.

that's the error that made me use your Projects instead of the nuget.

Thank you.

**Comment by 1iveowl** [comment] 2018-03-19 12:54
What version of Visual Studio are you using. I've only testet with VS 2017. 

Also, what version of Android are you compiling for?

**Comment by Eg-Virus** [comment] 2018-03-19 13:13
VS 2017 15.6.2 (the latest)
Android Compiling : Android 8.1 (Latest)
Phone : Android 8.0 Oreo (OnePlus version OxygenOS 5.0.1 (Latest))

**Comment by 1iveowl** [comment] 2018-03-19 13:34
And you are using this Nuget: [https://www.nuget.org/packages/SocketLite.PCL/](https://www.nuget.org/packages/SocketLite.PCL/)?

**Comment by Eg-Virus** [comment] 2018-03-19 13:42
![tcpclient connectasync cause error issue 17 1iveowlsocketlite - mozilla firefox](https://user-images.githubusercontent.com/4309859/37598879-830ecd10-2b94-11e8-9f97-1c0b6d11da44.jpg)

Yes, check the image in both the PCL and Android projects.

**Comment by Eg-Virus** [comment] 2018-03-19 13:44
the PCL is .NET Standard 2.0

**Comment by andrekiba** [comment] 2018-03-21 18:32
same problem also for me in Xamarin Forms, PCL .net standard 2.0, android 7.1, vs2017 15.6.3 :-(

**Comment by 1iveowl** [comment] 2018-03-22 13:13
I managed to recreate the issues I think you've been having. 

Could you try to see if NuGet 4.2.1 solves these issues and let me know?

Thank you

**Comment by 1iveowl** [comment] 2018-03-22 18:04
OK. Thank you. 

Sound like you are unable to connect. That must be something very different. Can you do some more troubleshooting?

**Comment by Eg-Virus** [comment] 2018-03-22 18:06
i'm now, i'll get back to you once i'm done trying :)

**Comment by andrekiba** [comment] 2018-03-22 18:19
I try this evening with Nuget 4.2.1 and I'll let you know :-) Thanks!

**Comment by Eg-Virus** [comment] 2018-03-22 18:51
Hi,
I think the connection problem was from my side because of Hercels listen to hidden IP not as i connect to.
SO, i able to connect , send and receive from Android and UWP. using your updated Nuget.

Thank you for your support in this issue.

**Closed** 2018-03-22 23:19 UTC
Labels: bug

**Comment by Eg-Virus** [comment] 2018-03-26 07:43
Hi again,
i have 2 point to ask you and i don't if it's related to the solved issue or not.
1) if i choose to make the connection secure, i can't control the received data or read it.
2) if the address i'm trying to connect is not available then the ConnectAsync return without exception and  tcpSocketClient.IsConnected is TRUE.

Thank you.

**Comment by 1iveowl** [comment] 2018-03-26 14:54
Could you please do these two things:

1) Create a new issue, as these are all new issues not related to this one
2) Create a Pull Request with a proposal for how to deal with this? 

In regards to 2) you should look at these two places:

- [.NET, iOS, Android and .NET Standard](https://github.com/1iveowl/SocketLite/blob/77ade10dfe4aa4969908328d187d8aab1c2b234f/src/main/CrossPlatform/SocketLite.NetStandard15/Services/TcpSocketClient.cs#L57)
- [UWP](https://github.com/1iveowl/SocketLite/blob/77ade10dfe4aa4969908328d187d8aab1c2b234f/src/main/CrossPlatform/SocketLite.UWP/Services/TcpSocketClient.cs#L43)

I'm not able to recreate the issue, so to move forward please do the two above.
